osx_image: xcode8
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods --pre # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/ATHMultiSelectionSegmentedControl.xcworkspace -scheme ATHMultiSelectionSegmentedControl-Example -sdk iphonesimulator10.0 -destination 'OS=10.0,name=iPhone 7 Plus' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
